// Banco del quiz de reglas: 100 preguntas por nivel (sorteo en quiz.js).
// Generado: node scripts/armar-quiz-banco.js
const PREGUNTAS = [
  { n: 1, t: "Cada equipo puede tener como máximo 7 jugadores en el campo durante un punto.", v: true, r: "5.1", e: "Máximo 7 y mínimo 5 jugadores por equipo en cada punto." },
  { n: 1, t: "Un partido lo gana el primer equipo que llega a 21 goles.", v: false, r: "4.2", e: "Gana el primer equipo que marca 15 goles." },
  { n: 1, t: "La media parte llega cuando un equipo marca por primera vez 8 goles.", v: true, r: "4.3", e: "El partido se divide en dos mitades y el corte es al llegar a 8." },
  { n: 1, t: "El lanzador puede correr con el disco si no tiene ningún defensor cerca.", v: false, r: "Introducción / 18.2", e: "El lanzador nunca puede correr con el disco: tiene que pivotar y pasarlo." },
  { n: 1, t: "Después de anotar un gol, el equipo que anotó es el que lanza el siguiente pull.", v: true, r: "4.5.3", e: "El equipo que anotó pasa a defensa y saca." },
  { n: 1, t: "El conteo va del 1 al 10 y entre cada número tiene que pasar al menos un segundo.", v: true, r: "9.1", e: "La marca dice “Contando” y cuenta del uno al diez, con al menos un segundo entre números." },
  { n: 1, t: "En Ultimate no hay árbitros: los propios jugadores cobran sus faltas.", v: true, r: "1.1", e: "Es un deporte autoarbitrado y sin contacto, basado en el Espíritu de Juego." },
  { n: 1, t: "Solo el jugador que recibió la falta puede cantarla.", v: true, r: "15.4", e: "La falta la pita únicamente quien la recibió, gritando “Falta”." },
  { n: 1, t: "Es gol si el receptor atrapa el disco con todos sus apoyos dentro de la zona de gol que ataca.", v: true, r: "14.1", e: "Además tiene que establecer la posesión y mantener la captura." },
  { n: 1, t: "Está permitido entregarle el disco en la mano a un compañero sin que vuele.", v: false, r: "13.2.3", e: "Eso es una “entrega” (handover) y provoca pérdida de posesión." },
  { n: 1, t: "Un tiempo muerto dura 75 segundos.", v: true, r: "20.2 / 20.3", e: "Tanto antes del pull como durante el punto, el tiempo muerto es de 75 segundos." },
  { n: 1, t: "Para pedir tiempo muerto hay que formar una “T” con las manos (o con una mano y el disco).", v: true, r: "20.1", e: "Y llamar “tiempo muerto” al equipo contrario." },
  { n: 1, t: "Felicitar a un rival por una buena jugada es un ejemplo de buen Espíritu de Juego.", v: true, r: "1.5.3", e: "Igual que presentarse al rival o retractarse de una llamada equivocada." },
  { n: 1, t: "Pedirle un pase a un jugador del equipo contrario es una táctica válida.", v: false, r: "1.6.6", e: "Es una violación clara del Espíritu de Juego." },
  { n: 1, t: "En los partidos mixtos se usa una proporción de género alternada de 4:3.", v: true, r: "5.4", e: "La proporción se va alternando entre puntos." },
  { n: 1, t: "Después de cada gol se pueden hacer cambios ilimitados de jugadores.", v: true, r: "5.3", e: "Siempre antes de que el equipo indique que está listo para el pull." },
  { n: 1, t: "En Ultimate cada equipo juega con 11 jugadores en el campo.", v: false, r: "5.1", e: "Son 7 por equipo (como mínimo 5). En playa se juega 5 contra 5." },
  { n: 1, t: "En Ultimate está permitido empujar o bloquear al rival con el cuerpo.", v: false, r: "1.1 / 12.6", e: "Es un deporte sin contacto: nadie puede iniciar contacto con un rival." },
  { n: 1, t: "Para anotar alcanza con que el disco entre volando en la zona de gol, aunque nadie lo atrape.", v: false, r: "14.1", e: "El gol se marca cuando un compañero atrapa un pase dentro de la zona de gol que ataca." },
  { n: 1, t: "Si un pase cae al suelo, el equipo que lo lanzó conserva el disco.", v: false, r: "13.1.1", e: "Si el disco toca el suelo sin que lo tenga el ataque, la posesión pasa al otro equipo." },
  { n: 1, t: "Burlarse del rival después de anotar un gol es parte del juego.", v: false, r: "1.6.4", e: "Las celebraciones irrespetuosas son una violación del Espíritu de Juego." },
  { n: 1, t: "El lanzador solo puede pasar el disco hacia adelante.", v: false, r: "Introducción", e: "Se puede pasar en cualquier dirección a cualquier compañero." },
  { n: 1, t: "El Ultimate se juega con un disco volador, no con una pelota.", v: true, r: "Introducción", e: "Es la base del deporte: se usa un disco (frisbee) y se anota atrapándolo en la zona de gol." },
  { n: 1, t: "Si te cae el disco al atraparlo, podés levantarlo y seguir como si nada.", v: false, r: "13.1", e: "Si el disco toca el suelo sin posesión del ataque, es turnover." },
  { n: 1, t: "Cada equipo tiene un capitán de espíritu, además del capitán de equipo.", v: true, r: "1 / Apéndice", e: "El espíritu de juego es tan importante que suele haber un spirit captain." },
  { n: 1, t: "Está permitido marcar al lanzador con las dos manos a la altura de la cara, siempre.", v: false, r: "18.1", e: "Hay reglas de marcaje (espacio de disco, wrapping, etc.); no todo vale." },
  { n: 1, t: "El partido empieza con un saque largo llamado “pull”.", v: true, r: "7", e: "La defensa lanza el pull para iniciar cada punto." },
  { n: 1, t: "Si no estás de acuerdo con una falta, podés pelearla a los gritos hasta que el otro se rinda.", v: false, r: "1.3 / 1.5", e: "Hay que discutir con respeto y, si no hay acuerdo, volver al último lanzador no disputado." },
  { n: 1, t: "Podés anotar un gol pasándole el disco a un compañero que está en la zona de gol que ataca.", v: true, r: "14.1", e: "El gol es una recepción válida dentro de la zona de gol atacante." },
  { n: 1, t: "La defensa puede quitarle el disco de las manos al atacante si está cerca.", v: false, r: "12.6 / 17.3", e: "No se puede iniciar contacto; quitarle el disco atrapado sería strip/falta." },
  { n: 1, t: "Antes de cada punto los equipos se alinean y la defensa saca.", v: true, r: "7.1 / 7.3", e: "Así empieza cada punto: alineación y pull." },
  { n: 1, t: "Si el marcador dice “diez”, el lanzador todavía tiene un segundo más para tirar.", v: false, r: "13.2.2", e: "Tiene que soltar el disco antes de que la marca empiece a decir “diez”." },
  { n: 1, t: "El Espíritu de Juego es opcional: solo importa en torneos grandes.", v: false, r: "1", e: "Es un principio central del Ultimate en todos los niveles." },
  { n: 1, t: "Podés pedir “tiempo” para atarte los cordones en cualquier momento sin que sea tiempo muerto.", v: false, r: "19 / 20", e: "Las paradas técnicas y los tiempos muertos tienen reglas; no se frena el juego por cualquier cosa." },
  { n: 1, t: "Si atrapás el disco, tenés que establecer un pie de pivote antes de tirar.", v: true, r: "18.2", e: "El pivote fija tu posición para pasar sin correr con el disco." },
  { n: 1, t: "Un equipo puede jugar con 3 jugadores si el resto está cansado.", v: false, r: "5.1", e: "El mínimo en campo es 5 (y el máximo 7)." },
  { n: 1, t: "Insultar al rival está permitido si fue una falta clara.", v: false, r: "1.6", e: "El irrespeto viola el Espíritu de Juego, aunque creas que tenías razón." },
  { n: 1, t: "El disco se puede pasar hacia atrás, a los costados o hacia adelante.", v: true, r: "Introducción", e: "No hay dirección obligatoria del pase." },
  { n: 1, t: "Si el ataque anota, al punto siguiente ataca otra vez el mismo equipo.", v: false, r: "4.5.3", e: "Quien anota pasa a defensa y hace el pull." },
  { n: 1, t: "Hay que presentarse y chocar los cinco con el rival es un buen gesto de espíritu.", v: true, r: "1.5", e: "El espíritu se demuestra también fuera de las jugadas polémicas." },
  { n: 1, t: "El Ultimate es un deporte de equipo.", v: true, r: "Introducción", e: "Se juega entre dos equipos que se enfrentan en el campo." },
  { n: 1, t: "El Ultimate se juega 1 contra 1.", v: false, r: "5.1", e: "Es un deporte de equipo: 7 contra 7 en campo (5 contra 5 en playa)." },
  { n: 1, t: "Para empezar el punto, la defensa lanza el disco hacia el ataque.", v: true, r: "7", e: "Ese saque se llama pull." },
  { n: 1, t: "El ataque es quien hace el pull al inicio del punto.", v: false, r: "7 / 4.5.3", e: "El pull lo hace la defensa." },
  { n: 1, t: "Si el disco cae al piso sin que el ataque lo tenga, cambia la posesión.", v: true, r: "13.1", e: "Eso es un turnover." },
  { n: 1, t: "Si el disco cae, el mismo equipo sigue atacando siempre.", v: false, r: "13.1", e: "Si toca el suelo sin posesión del ataque, el otro equipo toma el disco." },
  { n: 1, t: "No podés correr mientras tenés el disco.", v: true, r: "18.2", e: "Tenés que pivotar y pasar." },
  { n: 1, t: "Podés driblar el disco como en básquet.", v: false, r: "Introducción / 18.2", e: "No existe dribling: se pasa o se pivotea." },
  { n: 1, t: "El respeto al rival forma parte del juego.", v: true, r: "1", e: "Se llama Espíritu de Juego." },
  { n: 1, t: "Ganar justifica cualquier falta no cantada a propósito.", v: false, r: "1.6", e: "Esconder infracciones va contra el Espíritu de Juego." },
  { n: 1, t: "Un gol se anota atrapando el disco en la zona de gol rival.", v: true, r: "14.1", e: "Hace falta una recepción válida ahí." },
  { n: 1, t: "Metés gol pateando el disco al arco.", v: false, r: "14.1", e: "No hay arco: se anota atrapando un pase en la zona de gol." },
  { n: 1, t: "Los jugadores cobran sus propias faltas.", v: true, r: "1.1 / 15.4", e: "Es un deporte autoarbitrado." },
  { n: 1, t: "Siempre hay un árbitro central que pita todo.", v: false, r: "1.1", e: "En el reglamento WFDF básico no hay árbitros obligatorios." },
  { n: 1, t: "La marca puede contar hasta diez.", v: true, r: "9.1", e: "Si llega a decir “diez” antes de que sueltes, es stall-out." },
  { n: 1, t: "La marca cuenta hasta veinte.", v: false, r: "9.1", e: "El conteo va del uno al diez." },
  { n: 1, t: "Después de un gol hay cambios libres antes del siguiente punto.", v: true, r: "5.3", e: "Se pueden cambiar jugadores ilimitadamente entre puntos." },
  { n: 1, t: "No se puede cambiar a nadie en todo el partido.", v: false, r: "5.3", e: "Entre puntos los cambios son libres." },
  { n: 1, t: "Podés pasar el disco para atrás.", v: true, r: "Introducción", e: "El pase puede ir en cualquier dirección." },
  { n: 1, t: "Solo se puede progresar pasando hacia la zona de gol.", v: false, r: "Introducción", e: "Los pases atrás y laterales son legales." },
  { n: 1, t: "El mínimo de jugadores en campo por equipo es 5.", v: true, r: "5.1", e: "El máximo es 7." },
  { n: 1, t: "Hace falta tener 15 jugadores en el campo para empezar.", v: false, r: "5.1", e: "Son 7 por lado (mínimo 5)." },
  { n: 1, t: "Pedir un pase al rival es antideportivo.", v: true, r: "1.6.6", e: "Viola el Espíritu de Juego." },
  { n: 1, t: "Engañar al rival mintiendo sobre una regla está bien si ayuda a ganar.", v: false, r: "1.5 / 1.6", e: "Hay que ser honesto con las reglas y las llamadas." },
  { n: 1, t: "El tiempo muerto se pide haciendo una T con las manos.", v: true, r: "20.1", e: "Y avisando “tiempo muerto”." },
  { n: 1, t: "El tiempo muerto dura 5 minutos.", v: false, r: "20.2 / 20.3", e: "Dura 75 segundos." },
  { n: 1, t: "En mixta suele jugarse con proporción 4:3.", v: true, r: "5.4", e: "Y se alterna entre puntos." },
  { n: 1, t: "En mixta siempre hay 7 hombres en cancha.", v: false, r: "5.4", e: "La proporción de género está regulada (p. ej. 4:3)." },
  { n: 1, t: "Felicitar una buena jugada del rival es buen espíritu.", v: true, r: "1.5.3", e: "Es un ejemplo clásico del reglamento." },
  { n: 1, t: "Burlarse del rival después de un gol es parte de la cultura del Ultimate.", v: false, r: "1.6.4", e: "Las celebraciones irrespetuosas están mal vistas y violan el espíritu." },
  { n: 1, t: "Quien anota pasa a defender el punto siguiente.", v: true, r: "4.5.3", e: "Y por eso hace el pull." },
  { n: 1, t: "Quien anota sigue atacando de corrido como en rugby.", v: false, r: "4.5.3", e: "Se invierten los roles tras cada gol." },
  { n: 1, t: "El partido reglamentario se juega a 15 goles.", v: true, r: "4.2", e: "Gana el primero que llega a 15." },
  { n: 1, t: "El partido reglamentario se juega a 50 goles.", v: false, r: "4.2", e: "El objetivo estándar es 15." },
  { n: 1, t: "La media parte llega al llegar a 8 goles un equipo.", v: true, r: "4.3", e: "Ahí se corta el partido en dos mitades." },
  { n: 1, t: "No existe media parte en Ultimate.", v: false, r: "4.3", e: "Sí: cuando un equipo marca 8 por primera vez." },
  { n: 1, t: "Entregar el disco en la mano a un compañero es pérdida.", v: true, r: "13.2.3", e: "Se llama handover y es turnover." },
  { n: 1, t: "Podés pasarle el disco tocando las manos como en basquet si no hay marca.", v: false, r: "13.2.3", e: "El disco tiene que volar: la entrega es ilegal." },
  { n: 1, t: "Hay que mantener la captura para que cuente la recepción.", v: true, r: "12 / 14", e: "Si no controlás el disco, no hay posesión." },
  { n: 1, t: "Alcanza con rozar el disco para que sea recepción.", v: false, r: "12.1", e: "Hace falta controlar un disco que no esté girando." },
  { n: 1, t: "El campo tiene dos zonas de gol, una en cada extremo.", v: true, r: "2", e: "Se ataca una y se defiende la otra." },
  { n: 1, t: "Se anota en un aro colgado como en basketball.", v: false, r: "2 / 14", e: "Se anota en una zona rectangular de gol." },
  { n: 1, t: "Un contacto iniciado contra un rival puede ser falta.", v: true, r: "12.6 / 17", e: "El Ultimate es sin contacto." },
  { n: 1, t: "Los bloqueos con el cuerpo tipo básquet son legales.", v: false, r: "12.6 / 12.7", e: "Obstruir o cargar al rival no está permitido." },
  { n: 1, t: "Si no hay acuerdo en una jugada, se vuelve al último lanzador claro.", v: true, r: "1.12", e: "Es la resolución cuando no se ponen de acuerdo." },
  { n: 1, t: "Si no hay acuerdo, gana siempre el equipo local.", v: false, r: "1.12", e: "No: se vuelve al último lanzador no disputado." },
  { n: 1, t: "El lanzador establece un pie de pivote.", v: true, r: "18.2", e: "Ese pie fija su posición." },
  { n: 1, t: "El lanzador puede ir caminando con el disco si mira a la marca.", v: false, r: "18.2", e: "No puede caminar/correr con el disco." },
  { n: 1, t: "Decir “falta” es la forma de cantar una falta.", v: true, r: "15.4", e: "Lo hace quien la recibió." },
  { n: 1, t: "Cualquiera de la banda puede cobrar faltas de los que están adentro.", v: false, r: "15.4", e: "La falta la canta el jugador involucrado." },
  { n: 1, t: "El pull inicia cada punto.", v: true, r: "7", e: "Es el saque de la defensa." },
  { n: 1, t: "Cada punto empieza con un saque de córner.", v: false, r: "7", e: "Empieza con el pull." },
  { n: 1, t: "Podés retractarte si cantaste una falta mal.", v: true, r: "1.5", e: "Corregirse es buen espíritu." },
  { n: 1, t: "Una vez cantada una falta, nunca se puede retirar.", v: false, r: "1.5", e: "Retirar una llamada equivocada es correcto." },
  { n: 1, t: "El disco es el implemento oficial del juego.", v: true, r: "Introducción", e: "Sin disco no hay Ultimate." },
  { n: 1, t: "Se puede jugar un partido oficial con una pelota de tenis.", v: false, r: "Introducción", e: "El reglamento asume un disco volador." },
  { n: 1, t: "Los equipos se alinean antes del pull.", v: true, r: "7.3", e: "Ataque y defensa tienen posiciones iniciales." },
  { n: 1, t: "El ataque puede salir corriendo a mitad de campo antes del pull sin restricciones.", v: false, r: "7.3", e: "Hay reglas de alineación y offside." },
  { n: 1, t: "Gritarle insultos al marcador está mal.", v: true, r: "1.6", e: "Es falta de espíritu / conducta antideportiva." },
  { n: 1, t: "Si te están marcando fuerte, podés empujarlo para hacerte espacio.", v: false, r: "12.6", e: "Iniciar contacto es falta." },
  { n: 2, t: "Las líneas laterales y de fondo forman parte del campo de juego.", v: false, r: "2.3 / 11.1", e: "Las líneas perimetrales no son parte del campo: pisarlas es estar fuera." },
  { n: 2, t: "La línea de gol forma parte de la zona de gol.", v: false, r: "2.4", e: "La línea de gol es parte de la zona central, no de la zona de gol." },
  { n: 2, t: "La marca solo puede contar si está a menos de 3 metros del pivote del lanzador.", v: true, r: "9.3.2", e: "Si se aleja más de 3 metros, el conteo se tiene que reiniciar." },
  { n: 2, t: "Si el lanzador no soltó el disco antes de que la marca empiece a decir “diez”, es pérdida de posesión.", v: true, r: "13.2.2", e: "Eso es un “stall-out” y el disco pasa al otro equipo." },
  { n: 2, t: "Si un atacante y un defensor atrapan el disco al mismo tiempo, la posesión es para la defensa.", v: false, r: "12.3", e: "Si lo atrapan simultáneamente, el ataque conserva la posesión." },
  { n: 2, t: "Cualquier contacto menor entre jugadores que van al mismo punto siempre es falta.", v: false, r: "12.8", e: "El contacto menor al ir al mismo punto debe minimizarse, pero no es falta." },
  { n: 2, t: "Ir a buscar el disco (“hacer una jugada al disco”) justifica iniciar contacto con un rival.", v: false, r: "12.6.1", e: "Nunca hay justificación para iniciar contacto, ni siquiera por jugar el disco." },
  { n: 2, t: "Si después de discutir no hay acuerdo sobre una jugada, el disco vuelve al último lanzador no disputado.", v: true, r: "1.12", e: "Cuando no está claro qué pasó, se vuelve al último lanzador sin discusión." },
  { n: 2, t: "En el pull, un defensor puede tocar el disco antes de que lo toque un atacante o el suelo.", v: false, r: "7.7", e: "La defensa no puede tocar el pull hasta que lo toque un atacante o el suelo." },
  { n: 2, t: "Si un atacante toca el pull en el aire y no logra atraparlo, es pérdida de posesión.", v: true, r: "7.8", e: "Eso es un “pull caído” y la posesión pasa a la defensa." },
  { n: 2, t: "Antes del pull, los atacantes deben tener un pie sobre la línea de gol que defienden.", v: true, r: "7.3", e: "Y no pueden cambiar de lugar entre ellos hasta que se lance el pull." },
  { n: 2, t: "El brick se pide extendiendo completamente un brazo por encima de la cabeza.", v: true, r: "7.12", e: "Hay que señalizarlo así antes de levantar el disco del suelo." },
  { n: 2, t: "El disco puede volar por fuera de la línea lateral, volver al campo y seguir en juego.", v: true, r: "11.7", e: "El disco solo sale cuando toca el área de fuera o a un atacante que está fuera." },
  { n: 2, t: "Para que una captura sea válida alcanza con tocar el disco con una mano mientras todavía gira.", v: false, r: "12.1", e: "Captura es tener un disco que no gira entre al menos dos partes del cuerpo." },
  { n: 2, t: "El lanzador puede tirar el disco al aire y atraparlo él mismo si nadie más lo tocó.", v: false, r: "13.2.5", e: "Eso es un “autopase” y provoca pérdida de posesión." },
  { n: 2, t: "Pasos (“travel”) es una infracción y no detiene el juego.", v: true, r: "15.2 / 18.2.5", e: "Se corrige el pivote y el juego sigue sin detenerse." },
  { n: 2, t: "Los jugadores en la banda, salvo los capitanes, no deberían meterse en las discusiones.", v: true, r: "1.10.2", e: "Deciden los jugadores involucrados y los que mejor vieron la jugada." },
  { n: 2, t: "Si un jugador tiene una herida que sangra, hay que pedir una parada técnica.", v: true, r: "19.2.1", e: "Tiene 70 segundos para solucionarlo." },
  { n: 2, t: "Si el pull sale del campo por la línea lateral, el ataque puede poner el disco donde salió o pedir brick.", v: true, r: "7.12", e: "Es la elección típica ante un pull out-of-bounds (según el caso)." },
  { n: 2, t: "Un receptor que salta desde dentro, atrapa en el aire y cae fuera, hace una recepción válida.", v: false, r: "11.3 / 11.4", e: "Al caer fuera pasa a estar fuera: si ese es su primer contacto con el suelo, la recepción no vale." },
  { n: 2, t: "La marca tiene que estar a no menos de un diámetro de disco del pivote (espacio de disco).", v: true, r: "18.1.1.3", e: "Acercarse más es infracción de marcaje, salvo que lo cause solo el lanzador." },
  { n: 2, t: "Si el disco toca la línea lateral y rebota hacia adentro, sigue en juego.", v: false, r: "11.1 / 11.7", e: "La línea es fuera: si el disco toca fuera, está fuera." },
  { n: 2, t: "Un “turnover” por recepción incompleta le da la posesión al otro equipo donde cayó el disco.", v: true, r: "13.1", e: "La nueva ofensiva pone el pivote ahí (con los tiempos de la regla 8.5)." },
  { n: 2, t: "El lanzador puede demorar todo lo que quiera en poner el pivote después de atrapar.", v: false, r: "8.5 / 18.2", e: "Hay plazos para establecer el pivote y poner el disco en juego." },
  { n: 2, t: "Si dos atacantes atrapan el disco juntos, la posesión es del que lo controle primero claramente.", v: true, r: "12", e: "Tiene que haber una posesión clara; si no, se resuelve según las reglas de posesión." },
  { n: 2, t: "Cantar “falta” sin estar involucrado en el contacto es la forma correcta de ayudar al equipo.", v: false, r: "15.4", e: "La falta la canta quien la recibió." },
  { n: 2, t: "Después de un gol, los equipos tienen tiempo limitado para alinearse antes del siguiente pull.", v: true, r: "7 / 8", e: "Hay tiempos entre puntos; demorarse de más puede sancionarse según el apéndice/reglas de evento." },
  { n: 2, t: "Un defensor puede “poach” (dejar a su marca) siempre que no haga contacto ilegal.", v: true, r: "12 / Introducción", e: "Cambiar de marca o ayudar es táctica válida; lo ilegal es el contacto y ciertas obstrucciones." },
  { n: 2, t: "Si el ataque toca el pull y lo deja caer, la defensa puede arrancar desde ahí con posesión.", v: true, r: "7.8", e: "Es un pull caído: turnover para el ataque." },
  { n: 2, t: "La zona de gol mide lo mismo que la zona central del campo.", v: false, r: "2", e: "Las zonas de gol son más cortas que la zona central (medidas oficiales del campo)." },
  { n: 2, t: "Si hay discusión y no se ponen de acuerdo, un espectador puede decidir por ellos.", v: false, r: "1.10 / 1.12", e: "Deciden los jugadores involucrados (y quienes mejor vieron); si no hay acuerdo, se vuelve atrás." },
  { n: 2, t: "El conteo se dice en el idioma que elija la marca, aunque el torneo sea en español.", v: true, r: "9.1", e: "Lo importante es la cadencia (al menos un segundo) y que sea audible; el reglamento no impone el idioma." },
  { n: 2, t: "Un pase que toca el piso y lo agarra un compañero antes de que se detenga sigue siendo válido.", v: false, r: "13.1.1", e: "Si el disco toca el suelo sin posesión del ataque, es turnover." },
  { n: 2, t: "Si te llaman travel y no estás de acuerdo, podés contestar y el juego se detiene para resolverlo.", v: true, r: "15 / 18.2", e: "Las infracciones se pueden contestar; entonces se resuelve la discusión." },
  { n: 2, t: "El brick se marca a 15 metros de la línea de gol que defiende el ataque.", v: false, r: "2 / 7.12", e: "La marca de brick está a 18 metros (en campo estándar) de la línea de gol." },
  { n: 2, t: "Un jugador lesionado puede pedir parada técnica para atenderse.", v: true, r: "19", e: "Hay procedimientos específicos para lesiones y sangrado." },
  { n: 2, t: "Si el defensor tippea el disco y un atacante lo atrapa, la posesión es del ataque.", v: true, r: "12 / 13", e: "Tocar el disco no es turnover por sí solo; importa quién establece posesión después." },
  { n: 2, t: "Correr hacia el lanzador para “lay out” y golpearlo está bien si llegás al disco.", v: false, r: "12.6 / 17.1", e: "Iniciar contacto o jugar peligroso es falta, aunque vayas al disco." },
  { n: 2, t: "Después de un turnover en la zona de gol del nuevo ataque, puede haber más tiempo para poner el pivote.", v: true, r: "8.5.1.2", e: "En zona de gol son 20 segundos; en zona central, 10." },
  { n: 2, t: "El “stall” lo cuenta cualquier compañero de la marca desde la banda.", v: false, r: "9.3", e: "Cuenta la marca que está defendiendo al lanzador (con las condiciones de distancia)." },
  { n: 2, t: "Las líneas perimetrales no forman parte del campo.", v: true, r: "2.3 / 11.1", e: "Pisar la línea es estar fuera." },
  { n: 2, t: "Pisar la línea lateral cuenta como dentro.", v: false, r: "11.1", e: "La línea es fuera de límites." },
  { n: 2, t: "La línea de gol es parte de la zona central.", v: true, r: "2.4", e: "No forma parte de la zona de gol." },
  { n: 2, t: "La línea de gol cuenta como zona de gol.", v: false, r: "2.4", e: "Es parte del playing field proper central." },
  { n: 2, t: "La marca cuenta solo si está a menos de 3 metros del pivote.", v: true, r: "9.3.2", e: "Si se aleja, reinicia." },
  { n: 2, t: "La marca puede contar desde mitad de cancha.", v: false, r: "9.3.2", e: "Tiene que estar cerca del pivote (< 3 m)." },
  { n: 2, t: "Stall-out es pérdida de posesión.", v: true, r: "13.2.2", e: "Si llegan a “diez” antes de que sueltes." },
  { n: 2, t: "Stall-out solo advierte: seguís con el disco.", v: false, r: "13.2.2", e: "Es turnover." },
  { n: 2, t: "Recepción simultánea ataque-defensa: se queda el ataque.", v: true, r: "12.3", e: "El ataque conserva la posesión." },
  { n: 2, t: "Recepción simultánea: se queda la defensa.", v: false, r: "12.3", e: "Es al revés: posee el ataque." },
  { n: 2, t: "Contacto menor yendo al mismo punto no siempre es falta.", v: true, r: "12.8", e: "Hay que minimizarlo, pero no todo roce es falta." },
  { n: 2, t: "Cualquier roce en un salto compartido es falta automática.", v: false, r: "12.8", e: "El contacto menor incidental no necesariamente lo es." },
  { n: 2, t: "Ir al disco no justifica iniciar contacto.", v: true, r: "12.6.1", e: "Nunca hay justificación para iniciar contacto." },
  { n: 2, t: "Si vas al disco podés cargar al rival.", v: false, r: "12.6.1", e: "Eso es falta." },
  { n: 2, t: "La defensa no puede tocar el pull antes que el ataque o el suelo.", v: true, r: "7.7", e: "Si lo toca, es infracción." },
  { n: 2, t: "Un defensor puede interceptar el pull en el aire libremente.", v: false, r: "7.7", e: "No puede tocar el pull antes." },
  { n: 2, t: "Tocar el pull y no atraparlo es pull caído.", v: true, r: "7.8", e: "Turnover para el ataque." },
  { n: 2, t: "Si tocás el pull y se cae, lo podés levantar igual.", v: false, r: "7.8", e: "Pierden la posesión." },
  { n: 2, t: "Antes del pull el ataque pone un pie en su línea de gol.", v: true, r: "7.3", e: "Y no se reordenan hasta el saque." },
  { n: 2, t: "Antes del pull el ataque puede estar en cualquier lado del campo.", v: false, r: "7.3", e: "Deben alinearse en su línea de gol." },
  { n: 2, t: "El brick se señaliza con el brazo bien arriba.", v: true, r: "7.12", e: "Antes de levantar el disco." },
  { n: 2, t: "El brick se pide pisando el disco.", v: false, r: "7.12", e: "Se señaliza con el brazo extendido." },
  { n: 2, t: "El disco puede volar fuera y volver sin salir de juego.", v: true, r: "11.7", e: "Sale cuando toca fuera o a un atacante fuera." },
  { n: 2, t: "Si el disco cruza la línea en el aire ya es out.", v: false, r: "11.7", e: "En el aire puede volver; importa el contacto con fuera." },
  { n: 2, t: "Captura implica controlar un disco que no gira.", v: true, r: "12.1", e: "No alcanza con un toque." },
  { n: 2, t: "Un tip sin control ya es recepción.", v: false, r: "12.1", e: "Hace falta establecer posesión." },
  { n: 2, t: "Autopase es turnover.", v: true, r: "13.2.5", e: "No podés tirar y atrapar vos solo." },
  { n: 2, t: "Autopase es legal si nadie te marca.", v: false, r: "13.2.5", e: "Es ilegal siempre." },
  { n: 2, t: "Travel no detiene el juego como una falta.", v: true, r: "18.2.5", e: "Se corrige el pivote y se sigue." },
  { n: 2, t: "Todo travel congela el juego automáticamente.", v: false, r: "18.2.5", e: "Es una infracción que no detiene igual que una falta." },
  { n: 2, t: "Los de la banda no deberían meterse en discusiones.", v: true, r: "1.10.2", e: "Salvo roles específicos (p. ej. capitanes según contexto)." },
  { n: 2, t: "Toda la bancada puede votar cómo se resuelve una jugada.", v: false, r: "1.10.2", e: "Deciden quienes jugaron/vieron la jugada." },
  { n: 2, t: "Sangrado requiere parada técnica.", v: true, r: "19.2.1", e: "Hay un tiempo para resolverlo." },
  { n: 2, t: "Podés seguir jugando sangrando sin problema reglamentario.", v: false, r: "19.2.1", e: "Hay que atender la herida." },
  { n: 2, t: "Un tip del defensor no es turnover por sí solo.", v: true, r: "12 / 13", e: "Importa quién posee después." },
  { n: 2, t: "Si la defensa toca el disco, automáticamente es de ellos.", v: false, r: "13", e: "Solo si establecen posesión o el ataque pierde el disco al piso, etc." },
  { n: 2, t: "Layout limpio al disco es legal.", v: true, r: "12", e: "Si no hay contacto ilegal ni peligro." },
  { n: 2, t: "Todo layout es falta porque es peligroso.", v: false, r: "17.1", e: "El peligro se cobra si el juego es peligroso; un layout limpio vale." },
  { n: 2, t: "Después de turnover en zona de gol hay más tiempo de pivote.", v: true, r: "8.5", e: "20 s en zona de gol, 10 s en central." },
  { n: 2, t: "El pivote siempre hay que ponerlo en 3 segundos.", v: false, r: "8.5", e: "Los plazos son 10 o 20 segundos según la zona." },
  { n: 2, t: "Solo la marca cuenta el stall.", v: true, r: "9.3", e: "Con las condiciones de distancia." },
  { n: 2, t: "Un compañero desde la banda puede llevar el conteo oficial.", v: false, r: "9.3", e: "Cuenta la marca." },
  { n: 2, t: "Poach defensivo es legal si no hay infracción.", v: true, r: "Introducción", e: "Dejar una marca para ayudar es táctica." },
  { n: 2, t: "Cambiar de marca está prohibido.", v: false, r: "Introducción", e: "No está prohibido por sí solo." },
  { n: 2, t: "Contestar un travel abre la discusión.", v: true, r: "15", e: "Se puede no estar de acuerdo y resolver." },
  { n: 2, t: "El travel no se puede contestar nunca.", v: false, r: "15", e: "Como otras infracciones, se puede discutir." },
  { n: 2, t: "Handover es turnover aunque ambos estén quietos.", v: true, r: "13.2.3", e: "El disco tiene que ser pasado, no entregado." },
  { n: 2, t: "Handover vale en la zona de gol.", v: false, r: "13.2.3", e: "Es ilegal en todo el campo." },
  { n: 2, t: "El receptor que salta de adentro y cae afuera pierde la recepción.", v: true, r: "11.3 / 11.4", e: "Su estado al aterrizar define si está out." },
  { n: 2, t: "Si saltaste de adentro, aunque caigas afuera la recepción vale.", v: false, r: "11.3", e: "Al caer fuera estás fuera." },
  { n: 2, t: "Espacio de disco: la marca no puede estar demasiado cerca del pivote.", v: true, r: "18.1.1.3", e: "Menos de un diámetro de disco es infracción (salvo causa del lanzador)." },
  { n: 2, t: "La marca puede pegarse al cuerpo del lanzador sin límite.", v: false, r: "18.1.1.3", e: "Hay distancia mínima (disco space)." },
  { n: 2, t: "Un pase al piso incompleto es turnover donde cayó.", v: true, r: "13.1", e: "La nueva ofensiva juega desde ahí." },
  { n: 2, t: "Un pase al piso vuelve al lanzador automáticamente.", v: false, r: "13.1", e: "Es pérdida de posesión." },
  { n: 2, t: "El ataque elige brick o el punto de salida en varios pulls out.", v: true, r: "7.12", e: "Es una elección del ataque." },
  { n: 2, t: "El brick lo elige siempre la defensa.", v: false, r: "7.12", e: "Lo pide/elige el ataque." },
  { n: 2, t: "Juego peligroso puede ser falta sin contacto.", v: true, r: "17.1.1", e: "No hace falta tocarse." },
  { n: 2, t: "Sin contacto nunca hay falta.", v: false, r: "17.1.1", e: "El juego peligroso no requiere contacto." },
  { n: 2, t: "No es cierto que las líneas laterales y de fondo forman parte del campo de juego.", v: true, r: "2.3 / 11.1", e: "Las líneas perimetrales no son parte del campo: pisarlas es estar fuera." },
  { n: 2, t: "No es cierto que la línea de gol forma parte de la zona de gol.", v: true, r: "2.4", e: "La línea de gol es parte de la zona central, no de la zona de gol." },
  { n: 3, t: "Si el pull cae directo fuera del campo, sin tocar el campo ni a un atacante, el ataque puede pedir “brick”.", v: true, r: "7.12", e: "Puede poner el disco en la marca de brick o donde salió del campo." },
  { n: 3, t: "Un defensor que pisa fuera de la línea lateral pasa a estar fuera de límites.", v: false, r: "11.2", e: "Los defensores siempre se consideran dentro de los límites." },
  { n: 3, t: "Un receptor que atrapa el disco con un pie apoyado sobre la línea lateral hace una recepción válida.", v: false, r: "11.1 / 11.4.1", e: "La línea es fuera de límites: si tocaba fuera al agarrar el disco, es turnover." },
  { n: 3, t: "Cualquier defensor puede cantar pasos (“travel”).", v: true, r: "15.5.1", e: "Los pasos los puede llamar cualquier defensor, no solo la marca." },
  { n: 3, t: "Hay doble marca si otro defensor, además de la marca, está a menos de 3 m del pivote sin marcar a otro atacante.", v: true, r: "18.1.1.5", e: "Solo cruzar esa zona no cuenta como doble marca." },
  { n: 3, t: "La doble marca solo la puede cantar el lanzador.", v: false, r: "15.5.1", e: "La doble marca la puede pitar cualquier atacante." },
  { n: 3, t: "Tras un turnover en la zona central, hay 10 segundos para poner el pivote desde que el disco se detiene.", v: true, r: "8.5.1.1", e: "En la zona de gol son 20 segundos." },
  { n: 3, t: "Durante el punto, cualquier jugador del equipo atacante puede pedir tiempo muerto.", v: false, r: "20.3", e: "Después del pull, solo el lanzador con el disco puede pedirlo." },
  { n: 3, t: "Si en la misma jugada hay faltas aceptadas de los dos equipos, el disco vuelve al último lanzador no disputado.", v: true, r: "17.9.1", e: "Son faltas compensatorias." },
  { n: 3, t: "Si se acepta una falta por strip en una recepción que hubiera sido gol, se concede el gol.", v: true, r: "17.3.2", e: "El strip es una falta que hace soltar un disco ya atrapado." },
  { n: 3, t: "El juego peligroso solo se considera falta si llega a haber contacto.", v: false, r: "17.1.1", e: "Es falta aunque no haya contacto." },
  { n: 3, t: "El lanzador puede pivotar en cualquier dirección mientras mantenga su punto de pivote.", v: true, r: "18.2.2", e: "Si levanta o mueve el pie de pivote antes de soltar el pase, son pasos." },
  { n: 3, t: "Si atrapás corriendo, podés pasarla sin frenar si no cambiás de dirección y das como mucho dos apoyos más.", v: true, r: "18.2.1.1", e: "Tampoco podés acelerar antes de soltar el pase." },
  { n: 3, t: "Después de un stall-out contestado, el conteo se reanuda en 8.", v: true, r: "9.5.3", e: "Se retoma con “Contando ocho”." },
  { n: 3, t: "Después de un incumplimiento de la defensa aceptado, el conteo vuelve a empezar desde 1.", v: true, r: "9.5.1", e: "Si el error lo aceptó la defensa, se reinicia en “Contando uno”." },
  { n: 3, t: "Después de una llamada de obstrucción (“pick”), el conteo se retoma como máximo en 6.", v: true, r: "9.5.5", e: "Para la mayoría de las demás llamadas, el conteo vuelve como máximo a seis." },
  { n: 3, t: "Un jugador en el aire conserva su estado dentro/fuera de límites hasta que vuelve a tocar el suelo.", v: true, r: "11.3.1", e: "Su estado se define recién al hacer contacto con el campo o con el área de fuera." },
  { n: 3, t: "Antes de cantar “pick”, el defensor puede esperar hasta 2 segundos para ver si la obstrucción afecta la jugada.", v: true, r: "18.3.1.1", e: "Lo mismo vale para las faltas indirectas (17.8.1.1)." },
  { n: 3, t: "Si la defensa se adelanta en el pull (offside) y el ataque lo cobra, debe dejar caer el disco y se juega como brick.", v: true, r: "7.5.2", e: "El ataque deja que el disco toque el suelo y reanuda como si hubiera pedido brick." },
  { n: 3, t: "Si el lanzador pide tiempo muerto cuando a su equipo no le quedan, se suman 2 segundos al conteo.", v: true, r: "20.4", e: "Si con eso el conteo llega a 10 o más, es stall-out." },
  { n: 3, t: "Si cualquier parte del cuerpo del defensor está por encima del punto de pivote del lanzador, es “wrapping”.", v: true, r: "18.1.1.4", e: "Salvo que la situación la cause solo el movimiento del lanzador." },
  { n: 3, t: "Si el lanzador se acerca al defensor y por eso queda a menos de un disco de distancia, es infracción de “espacio de disco” del defensor.", v: false, r: "18.1.1.3", e: "Si la cercanía la causa solo el movimiento del lanzador, no es infracción." },
  { n: 3, t: "Después de un turnover en una zona de gol, el pivote debe establecerse dentro de los 10 segundos.", v: false, r: "8.5.1.2", e: "En la zona de gol el plazo es de 20 segundos; en la zona central, 10." },
  { n: 3, t: "Después de un tiempo muerto pedido durante el punto, se pueden hacer cambios de jugadores libremente.", v: false, r: "20.3.1", e: "No se permiten cambios, salvo por lesión." },
  { n: 3, t: "Después de una infracción de pasos aceptada, el juego se detiene.", v: false, r: "18.2.5", e: "El juego no se detiene: se corrige el pivote y se sigue." },
  { n: 3, t: "Una falta indirecta hay que cantarla en el instante del contacto, sin poder esperar.", v: false, r: "17.8.1.1", e: "Se puede demorar hasta 2 segundos para ver si afecta la jugada." },
  { n: 3, t: "Después de un incumplimiento del ataque aceptado, el conteo se reinicia en 1.", v: false, r: "9.5.2", e: "Se retoma como máximo en 9, no desde 1." },
  { n: 3, t: "Un jugador con una herida que sangra tiene 3 minutos para solucionarlo.", v: false, r: "19.2.1.2", e: "Tiene 70 segundos; si necesita más, debe ser sustituido o su equipo usa un tiempo muerto." },
  { n: 3, t: "Después de un tiempo muerto, el disco lo puede retomar otro compañero como lanzador.", v: false, r: "20.3.3", e: "El lanzador tiene que seguir siendo el mismo." },
  { n: 3, t: "Al reanudar tras un tiempo muerto, los defensores eligen su posición antes que los atacantes.", v: false, r: "20.3.4 / 20.3.5", e: "Primero se ubican los atacantes y después los defensores." },
  { n: 3, t: "Si se acepta un travel y el lanzador ya había tirado un pase completo, el pase se anula igual.", v: false, r: "18.2.5", e: "El travel no detiene el juego de la misma forma que una falta: si el pase ya se completó según las reglas aplicables, se trata distinto a una falta en el aire." },
  { n: 3, t: "Un “double team” / doble marca se canta aunque el segundo defensor esté marcando a un cutter a menos de 3 m.", v: false, r: "18.1.1.5", e: "Si está marcando a otro atacante, no es doble marca." },
  { n: 3, t: "Después de un pick aceptado, los jugadores se reubican donde estaban al momento de la obstrucción.", v: true, r: "18.3", e: "El sentido del pick es restaurar el estado previo a la obstrucción." },
  { n: 3, t: "Si el lanzador finta y mueve el pivote, es travel aunque no suelte el disco.", v: true, r: "18.2", e: "Mover o levantar el pivote sin haber soltado el pase (salvo excepciones de recepción) es travel." },
  { n: 3, t: "Una falta “en el aire” sobre el receptor se resuelve donde caería el receptor, no donde estaba el contacto.", v: false, r: "17", e: "Por lo general la posesión se establece donde ocurrió la falta (con las excepciones del reglamento)." },
  { n: 3, t: "Si hay offside del ataque en el pull y la defensa lo cobra, el pull se rehace.", v: true, r: "7.5", e: "El offside del ataque se resuelve rehaciendo el pull (según el procedimiento de la regla)." },
  { n: 3, t: "El conteo después de una falta ofensiva aceptada se retoma como máximo en 9.", v: false, r: "9.5", e: "Depende de quién cometió la infracción; no siempre es “máximo 9”." },
  { n: 3, t: "Un receptor puede tippear el disco a un compañero a propósito (como asistencia) si nadie más lo toca ilegalmente.", v: true, r: "12 / 13", e: "El tip voluntario a un compañero es válido; no es handover ni autopase del lanzador." },
  { n: 3, t: "Si el marcador pierde la marca (se aleja más de 3 m) y vuelve, puede seguir el conteo desde donde quedó.", v: false, r: "9.3.2", e: "Si se aleja más de 3 m, el conteo debe reiniciarse." },
  { n: 3, t: "Wrapping incluye meter la mano por encima del pivote aunque no haya contacto.", v: true, r: "18.1.1.4", e: "Es una infracción de marcaje por la posición del cuerpo/brazo sobre el pivote." },
  { n: 3, t: "Si se contesta un stall-out, el lanzador conserva el disco y el conteo vuelve a 8.", v: true, r: "9.5.3", e: "Se retoma con “Contando ocho”." },
  { n: 3, t: "Un strip en zona de gol que hubiera sido gol concede el gol si se acepta la falta.", v: true, r: "17.3.2", e: "Es una de las excepciones donde la falta defensiva otorga el gol." },
  { n: 3, t: "Durante un tiempo muerto en el punto, el lanzador puede cambiar de lugar libremente en todo el campo.", v: false, r: "20.3", e: "Hay restricciones de posición al reanudar; el lanzador sigue siendo el mismo." },
  { n: 3, t: "Si un defensor hace un layout y toca el disco limpio sin contacto ilegal, la jugada vale aunque asuste al rival.", v: true, r: "12 / 17.1", e: "Jugar el disco sin contacto ilegal ni juego peligroso es válido." },
  { n: 3, t: "La línea de brick está dentro de la zona de gol.", v: false, r: "2 / 7.12", e: "La marca de brick está en la zona central, a distancia fija de la línea de gol." },
  { n: 3, t: "Si pedís tiempo muerto y tu equipo no tiene, el juego sigue y se aplica la penalización de conteo.", v: true, r: "20.4", e: "Se suman 2 segundos al conteo; puede terminar en stall-out." },
  { n: 3, t: "Un atacante puede cantar double team.", v: true, r: "15.5.1", e: "Cualquier atacante puede cantar la doble marca." },
  { n: 3, t: "Si el disco está atrapado entre el suelo y la mano, ya hay posesión.", v: false, r: "12.1", e: "Tiene que haber control de un disco que no gira; atraparlo contra el suelo no alcanza como captura limpia en muchos casos." },
  { n: 3, t: "Cualquier defensor puede cantar travel.", v: true, r: "15.5.1", e: "No solo la marca." },
  { n: 3, t: "Solo la marca puede cantar travel.", v: false, r: "15.5.1", e: "Cualquier defensor puede." },
  { n: 3, t: "Doble marca: segundo defensor <3 m sin marcar a otro.", v: true, r: "18.1.1.5", e: "Si marca a otro atacante, no es double team." },
  { n: 3, t: "Pasar cerca del pivote siempre es doble marca.", v: false, r: "18.1.1.5", e: "Hay que estar a menos de 3 m y sin marcar a otro." },
  { n: 3, t: "Cualquier atacante puede cantar doble marca.", v: true, r: "15.5.1", e: "No solo el lanzador." },
  { n: 3, t: "Solo el lanzador canta double team.", v: false, r: "15.5.1", e: "Cualquier atacante puede." },
  { n: 3, t: "Turnover en zona central: 10 s para el pivote.", v: true, r: "8.5.1.1", e: "Desde que el disco se detiene." },
  { n: 3, t: "Turnover en zona central: 30 s para el pivote.", v: false, r: "8.5.1.1", e: "Son 10 segundos." },
  { n: 3, t: "Durante el punto solo el lanzador pide tiempo muerto.", v: true, r: "20.3", e: "Después del pull." },
  { n: 3, t: "Cualquier atacante pide tiempo muerto a mitad del punto.", v: false, r: "20.3", e: "Solo el lanzador con el disco." },
  { n: 3, t: "Faltas compensatorias: vuelve al último lanzador no disputado.", v: true, r: "17.9.1", e: "Cuando ambas se aceptan en la misma jugada." },
  { n: 3, t: "Faltas compensatorias: el disco queda donde cayó.", v: false, r: "17.9.1", e: "Vuelve al último lanzador claro." },
  { n: 3, t: "Strip aceptado en gol: se concede el gol.", v: true, r: "17.3.2", e: "Excepción importante del strip." },
  { n: 3, t: "Strip en la zona de gol nunca puede dar gol.", v: false, r: "17.3.2", e: "Si hubiera sido gol, se concede." },
  { n: 3, t: "Juego peligroso no necesita contacto.", v: true, r: "17.1.1", e: "La peligrosidad basta." },
  { n: 3, t: "Juego peligroso solo existe con contacto.", v: false, r: "17.1.1", e: "Puede cobrarse sin contacto." },
  { n: 3, t: "Podés pivotar en cualquier dirección con el pivote fijo.", v: true, r: "18.2.2", e: "El pivote no se levanta." },
  { n: 3, t: "Solo se puede pivotar hacia la zona de gol.", v: false, r: "18.2.2", e: "Cualquier dirección es válida." },
  { n: 3, t: "Atrapando al correr: hasta dos apoyos más sin cambiar dirección ni acelerar.", v: true, r: "18.2.1.1", e: "Para soltar un pase legal." },
  { n: 3, t: "Atrapando al correr podés seguir 10 pasos si tirás.", v: false, r: "18.2.1.1", e: "Como máximo dos apoyos adicionales con condiciones." },
  { n: 3, t: "Stall-out contestado: se retoma en 8.", v: true, r: "9.5.3", e: "“Contando ocho”." },
  { n: 3, t: "Stall-out contestado: se retoma en 1.", v: false, r: "9.5.3", e: "Se retoma en 8." },
  { n: 3, t: "Incumplimiento defensivo aceptado: conteo desde 1.", v: true, r: "9.5.1", e: "Reinicio completo para el ataque." },
  { n: 3, t: "Incumplimiento defensivo aceptado: conteo en 9.", v: false, r: "9.5.1", e: "Vuelve a “Contando uno”." },
  { n: 3, t: "Pick: conteo como máximo en 6.", v: true, r: "9.5.5", e: "Como muchas otras llamadas." },
  { n: 3, t: "Pick: conteo siempre en 1.", v: false, r: "9.5.5", e: "Máximo en 6." },
  { n: 3, t: "En el aire conservás el estado hasta tocar suelo.", v: true, r: "11.3.1", e: "Dentro/fuera se define al aterrizar." },
  { n: 3, t: "En el aire ya sos out si cruzaste la línea imaginaria.", v: false, r: "11.3.1", e: "Importa el contacto con el suelo/fuera." },
  { n: 3, t: "Podés demorar hasta 2 s para cantar pick.", v: true, r: "18.3.1.1", e: "Para ver si afectó." },
  { n: 3, t: "El pick se puede cantar al final del punto.", v: false, r: "18.3.1.1", e: "La demora máxima es corta (~2 s)." },
  { n: 3, t: "Offside defensivo cobrado: se juega como brick.", v: true, r: "7.5.2", e: "El ataque deja caer y reanuda tipo brick." },
  { n: 3, t: "Offside defensivo siempre rehace el pull.", v: false, r: "7.5.2", e: "El procedimiento indicado es jugarlo como brick." },
  { n: 3, t: "Tiempo muerto sin tener: +2 al conteo.", v: true, r: "20.4", e: "Puede producir stall-out." },
  { n: 3, t: "Tiempo muerto sin tener: expulsión.", v: false, r: "20.4", e: "La sanción es sumar 2 al conteo." },
  { n: 3, t: "Wrapping: parte del defensor sobre el pivote.", v: true, r: "18.1.1.4", e: "Salvo que lo cause solo el lanzador." },
  { n: 3, t: "Wrapping solo existe si hay contacto con la mano.", v: false, r: "18.1.1.4", e: "Es por la posición sobre el pivote." },
  { n: 3, t: "Si el lanzador se mete encima de la marca, no es disco space del defensor.", v: true, r: "18.1.1.3", e: "Lo tiene que causar el defensor." },
  { n: 3, t: "Cualquier cercanía es disco space del defensor.", v: false, r: "18.1.1.3", e: "Si la causa el lanzador, no." },
  { n: 3, t: "Turnover en zona de gol: 20 s de pivote.", v: true, r: "8.5.1.2", e: "Más tiempo que en central." },
  { n: 3, t: "Turnover en zona de gol: 5 s de pivote.", v: false, r: "8.5.1.2", e: "Son 20 segundos." },
  { n: 3, t: "Tiempo muerto en el punto: sin cambios (salvo lesión).", v: true, r: "20.3.1", e: "No es un entrepunto." },
  { n: 3, t: "Tiempo muerto en el punto: cambios libres.", v: false, r: "20.3.1", e: "No se permiten cambios libres." },
  { n: 3, t: "Travel aceptado: el juego no se detiene.", v: true, r: "18.2.5", e: "Se corrige pivote y sigue." },
  { n: 3, t: "Travel aceptado: siempre hay stoppage largo.", v: false, r: "18.2.5", e: "No detiene como una falta." },
  { n: 3, t: "Falta indirecta: hasta 2 s para cantarla.", v: true, r: "17.8.1.1", e: "Para ver si afectó." },
  { n: 3, t: "Falta indirecta: solo en el instante exacto o no vale.", v: false, r: "17.8.1.1", e: "Hay una demora breve permitida." },
  { n: 3, t: "Incumplimiento del ataque aceptado: conteo máx. en 9.", v: true, r: "9.5.2", e: "No vuelve a 1." },
  { n: 3, t: "Incumplimiento del ataque aceptado: conteo en 1.", v: false, r: "9.5.2", e: "Se retoma como máximo en 9." },
  { n: 3, t: "Sangrado: 70 segundos.", v: true, r: "19.2.1.2", e: "Si no, cambio o tiempo muerto." },
  { n: 3, t: "Sangrado: 10 minutos.", v: false, r: "19.2.1.2", e: "Son 70 segundos." },
  { n: 3, t: "Tras tiempo muerto el lanzador es el mismo.", v: true, r: "20.3.3", e: "No podés cambiar quién tiene el disco." },
  { n: 3, t: "Tras tiempo muerto puede tirar cualquiera.", v: false, r: "20.3.3", e: "Sigue el mismo lanzador." },
  { n: 4, t: "Si el pull toca el campo dentro de la zona de gol atacada y el ataque no lo toca, puede elegir poner el pivote en la marca de brick.", v: true, r: "7.11 / 7.12", e: "Es un caso de “brick”: el ataque elige brick o el punto más cercano donde el disco cruzó el perímetro." },
  { n: 4, t: "Un strip solo se puede cantar si el disco ya estaba bajo control del receptor.", v: true, r: "17.3", e: "Strip es hacer que un oponente suelte un disco que ya había atrapado." },
  { n: 4, t: "Si se acepta una falta ofensiva en una recepción que hubiera sido gol, el gol se anula y el defensor se queda con el disco.", v: false, r: "17.2 / 17.6", e: "Si la falta ofensiva se acepta, es turnover; no hay gol." },
  { n: 4, t: "Después de una falta defensiva aceptada en un intento de recepción, el receptor se queda con el disco donde ocurrió la falta.", v: true, r: "17.2.2", e: "Salvo reglas especiales (como strip en gol), la posesión queda donde se cometió." },
  { n: 4, t: "Si el marcador empieza el conteo antes de que el disco esté en juego, el conteo es válido igual.", v: false, r: "9.3", e: "Solo se puede contar cuando el disco está en juego y se cumplen las condiciones de la marca." },
  { n: 4, t: "Un “fast count” se corrige reiniciando el conteo en el último número dicho correctamente.", v: false, r: "9.5 / 18.1", e: "Ante un fast count, el conteo se reinicia en el número anterior al último dicho incorrectamente (según el caso)." },
  { n: 4, t: "Si hay una llamada y el disco está en el aire, los jugadores deben seguir jugando hasta que la posesión se establezca.", v: true, r: "15.7", e: "El juego continúa hasta que se determina la posesión; después se resuelve la llamada." },
  { n: 4, t: "Un receptor que atrapa el disco en la zona de gol y sale corriendo hacia la zona central anula el gol.", v: false, r: "14.1 / 14.2", e: "Si estableció posesión dentro de la zona de gol, el gol vale aunque después salga." },
  { n: 4, t: "La marca puede contar aunque haya otro defensor a menos de 3 m del pivote marcando a otro atacante.", v: true, r: "9.3 / 18.1.1.5", e: "Eso no es doble marca: la doble marca es cuando ese defensor no está marcando a nadie." },
  { n: 4, t: "Si el ataque pide brick y también hubo offside de la defensa, el brick prevalece sobre el offside.", v: true, r: "7.5 / 7.12", e: "El ataque puede elegir cómo reanudar; el brick es una opción válida en ese contexto." },
  { n: 4, t: "Un “pick” se puede cantar aunque el defensor no estuviera a menos de 3 metros del atacante al momento de la obstrucción.", v: false, r: "18.3.1", e: "Para cantar pick, el defensor tiene que estar a 3 metros o menos del atacante al que marca." },
  { n: 4, t: "Tras un turnover, si el nuevo lanzador tarda de más en establecer el pivote, cualquier rival puede cantar “violation”.", v: true, r: "8.5 / 15", e: "Exceder el tiempo para poner el pivote es una infracción que se puede cobrar." },
  { n: 4, t: "Si un pase es interceptado y el interceptor comete travel al recibir, el disco vuelve al lanzador anterior.", v: false, r: "18.2.5 / 13", e: "El turnover ya ocurrió: se corrige el pivote del nuevo poseedor y el juego sigue." },
  { n: 4, t: "En playa, el máximo de jugadores por equipo en el campo es 5.", v: true, r: "Apéndice / 5.1", e: "Ultimate playa se juega 5 contra 5; el campo completo es 7 contra 7." },
  { n: 4, t: "Si el pull aterriza en la zona de gol y el ataque lo deja quieto a propósito para pedir brick, es válido.", v: true, r: "7.11 / 7.12", e: "Ante ciertas trayectorias del pull, el ataque puede elegir brick." },
  { n: 4, t: "Un travel cantado después de que el pase ya fue atrapado siempre anula la recepción.", v: false, r: "18.2.5", e: "El travel no funciona igual que una falta en el aire: el juego no se “congela” de la misma manera." },
  { n: 4, t: "Si hay una falta y un travel cantados en la misma acción, siempre gana la falta.", v: false, r: "15 / 17 / 18", e: "Se resuelve según qué infracciones se aceptan y cómo afectan la posesión." },
  { n: 4, t: "El marcador puede contar en voz baja si el lanzador está cerca.", v: false, r: "9.1", e: "El conteo tiene que ser audible para el lanzador." },
  { n: 4, t: "Si un defensor está “en el disc” (jugando el disco) puede iniciar contacto leve con el receptor.", v: false, r: "12.6.1", e: "Ir al disco no justifica iniciar contacto." },
  { n: 4, t: "Después de un turnover, el nuevo ataque puede empezar a contar en cuanto el rival suelta el disco, sin pivote.", v: false, r: "9.3 / 8.5", e: "El disco tiene que estar en juego y cumplirse las condiciones de la marca." },
  { n: 4, t: "Un receptor que controla el disco y después lo pierde por contacto del defensor puede cantar strip.", v: true, r: "17.3", e: "Strip es hacer soltar un disco ya atrapado." },
  { n: 4, t: "Si el ataque pide brick, debe señalizarlo antes de recoger el disco del suelo.", v: true, r: "7.12", e: "La señal de brick (brazo extendido arriba) va antes de levantar el disco." },
  { n: 4, t: "Un pick se puede cantar 5 segundos después, si recién ahí te diste cuenta.", v: false, r: "18.3.1.1", e: "Como máximo podés demorar unos 2 segundos para ver si afectó la jugada." },
  { n: 4, t: "Si el lanzador está en la zona de gol propia tras un turnover, tiene 20 segundos para el pivote.", v: true, r: "8.5.1.2", e: "En zona de gol el plazo es 20 segundos." },
  { n: 4, t: "La doble marca solo importa si el segundo defensor está quieto; si camina, no cuenta.", v: false, r: "18.1.1.5", e: "Cuenta la distancia y si está marcando a alguien, no si está quieto o no." },
  { n: 4, t: "Si se acepta una falta defensiva en un pase incompleto, el receptor se queda con el disco.", v: true, r: "17.2", e: "La falta aceptada suele devolver/otorgar la posesión al ofendido según el caso." },
  { n: 4, t: "Un autopase es legal si el disco toca el piso primero.", v: false, r: "13.2.5 / 13.1", e: "Si toca el piso es turnover; y atraparlo vos mismo sin que otro lo toque es autopase ilegal." },
  { n: 4, t: "En mixta, cambiar la proporción de género a mitad del punto está permitido si hay lesión.", v: false, r: "5.4 / 19", e: "La proporción se define para el punto; las excepciones de lesión siguen reglas específicas, no un cambio libre de ratio." },
  { n: 4, t: "Si el defensor “mirrors” los brazos del lanzador sin entrar en wrapping ni disco space, es legal.", v: true, r: "18.1", e: "Marcar con los brazos es válido mientras se respeten espacio de disco, wrapping y contacto." },
  { n: 4, t: "Después de un brick, el conteo puede empezar apenas el pivote está establecido y hay marca legal.", v: true, r: "9.3 / 7.12", e: "Una vez el disco está en juego con pivote y marca en regla, se puede contar." },
  { n: 4, t: "Un capitán de la banda puede cantar falta por un compañero que está en el campo.", v: false, r: "15.4", e: "La falta la canta quien la recibió." },
  { n: 4, t: "Si hay sangrado, el jugador tiene 70 segundos; si no llega, debe salir o usar tiempo muerto.", v: true, r: "19.2.1", e: "Ese es el procedimiento de herida que sangra." },
  { n: 4, t: "Un pase que sale del campo y vuelve sin tocar nada sigue vivo.", v: true, r: "11.7", e: "El disco en el aire puede viajar fuera y volver; sale cuando toca fuera o a un atacante fuera." },
  { n: 4, t: "Si el marcador dice los números más rápido que un segundo, el lanzador puede cantar fast count.", v: true, r: "9.1 / 18.1", e: "El intervalo mínimo es de un segundo; acelerar es infracción de conteo." },
  { n: 4, t: "Strip requiere disco ya controlado.", v: true, r: "17.3", e: "Si todavía no había captura, no es strip." },
  { n: 4, t: "Strip se canta en cualquier tip del defensor.", v: false, r: "17.3", e: "Es hacer soltar un disco atrapado." },
  { n: 4, t: "Falta ofensiva aceptada en recepción de gol: no hay gol.", v: true, r: "17.2 / 17.6", e: "Es turnover / se anula el gol." },
  { n: 4, t: "Falta ofensiva en el endzone igual da gol si atrapó.", v: false, r: "17", e: "Si se acepta la falta ofensiva, no hay gol." },
  { n: 4, t: "Falta defensiva en intento de recepción: receptor con disco.", v: true, r: "17.2.2", e: "Salvo excepciones." },
  { n: 4, t: "Falta defensiva en recepción incompleta: siempre rehace el pull.", v: false, r: "17.2", e: "Se otorga posesión al receptor ofendido." },
  { n: 4, t: "No se puede contar con el disco muerto.", v: true, r: "9.3", e: "El disco tiene que estar en juego." },
  { n: 4, t: "Se puede empezar a contar en cuanto el rival suelta el disco al piso.", v: false, r: "9.3", e: "Hace falta que esté en juego y haya marca legal." },
  { n: 4, t: "Con disco en el aire tras una llamada, se sigue hasta la posesión.", v: true, r: "15.7", e: "Después se resuelve." },
  { n: 4, t: "Con disco en el aire tras una llamada, todos se detienen en el acto.", v: false, r: "15.7", e: "Se juega hasta establecer posesión." },
  { n: 4, t: "Gol válido aunque después salgas de la zona de gol.", v: true, r: "14.1 / 14.2", e: "Importa dónde estableciste posesión." },
  { n: 4, t: "Si celebrás saliendo del endzone se anula el gol.", v: false, r: "14", e: "Salir después no anula la posesión ya establecida." },
  { n: 4, t: "Defensor <3 m marcando a otro no es doble marca.", v: true, r: "18.1.1.5", e: "Tiene que no estar marcando a nadie." },
  { n: 4, t: "Dos defensores cerca del pivote siempre es double team.", v: false, r: "18.1.1.5", e: "Depende de si el segundo marca a alguien." },
  { n: 4, t: "Pick requiere estar a ≤3 m del atacante marcado.", v: true, r: "18.3.1", e: "Si estás lejos, no es pick." },
  { n: 4, t: "Pick se canta desde cualquier distancia.", v: false, r: "18.3.1", e: "Hay requisito de proximidad." },
  { n: 4, t: "Tardar de más en el pivote se puede cobrar.", v: true, r: "8.5 / 15", e: "Es una violation de tiempo." },
  { n: 4, t: "El pivote se puede demorar sin límite.", v: false, r: "8.5", e: "Hay plazos de 10/20 s." },
  { n: 4, t: "Travel del interceptor no devuelve el disco al lanzador previo.", v: true, r: "18.2.5 / 13", e: "El turnover ya pasó; se corrige pivote." },
  { n: 4, t: "Travel tras intercepción anula el turnover.", v: false, r: "13 / 18", e: "No vuelve automáticamente al lanzador anterior." },
  { n: 4, t: "Playa: 5 contra 5.", v: true, r: "Apéndice / 5.1", e: "Campo completo es 7." },
  { n: 4, t: "Playa: 7 contra 7 igual que césped.", v: false, r: "Apéndice", e: "En playa es 5 vs 5." },
  { n: 4, t: "Brick hay que señalizarlo antes de levantar el disco.", v: true, r: "7.12", e: "Si no, no cuenta como pedido a tiempo." },
  { n: 4, t: "Podés pedir brick después de caminar 10 metros con el disco.", v: false, r: "7.12", e: "La señal es previa a recogerlo." },
  { n: 4, t: "Fast count se puede cantar si acelera el ritmo.", v: true, r: "9.1 / 18.1", e: "Menos de un segundo entre números." },
  { n: 4, t: "La marca puede contar a velocidad libre.", v: false, r: "9.1", e: "Mínimo un segundo entre números." },
  { n: 4, t: "Defensor puede jugar el disco desde fuera.", v: true, r: "11.2", e: "Los defensores se consideran in-bounds." },
  { n: 4, t: "Defensor con un pie fuera no puede tocar el disco.", v: false, r: "11.2", e: "La defensa no queda out como el ataque." },
  { n: 4, t: "Bobblear y después controlar puede ser captura.", v: true, r: "12.1", e: "La posesión se establece al controlar." },
  { n: 4, t: "Si el disco te rebota en la mano ya no podés atraparlo.", v: false, r: "12.1", e: "Podés terminar de controlar después del bobble." },
  { n: 4, t: "Offside hay que cantarlo para que se aplique.", v: true, r: "7.5 / 15", e: "Si nadie lo cobra, el punto sigue." },
  { n: 4, t: "El offside se autoaplica aunque nadie diga nada.", v: false, r: "15", e: "Hace falta la llamada." },
  { n: 4, t: "Marcaje con brazos es legal sin wrapping ni disco space.", v: true, r: "18.1", e: "Respetá las restricciones de marcaje." },
  { n: 4, t: "Levantar los brazos para marcar es siempre wrapping.", v: false, r: "18.1.1.4", e: "Wrapping es estar sobre el pivote." },
  { n: 4, t: "Capitán de banda no canta faltas ajenas.", v: true, r: "15.4", e: "Las canta quien las recibe." },
  { n: 4, t: "El capitán puede pitar faltas por sus jugadores.", v: false, r: "15.4", e: "No reemplaza al jugador involucrado." },
  { n: 4, t: "Pull tocado por defensa antes de tiempo es infracción.", v: true, r: "7.7", e: "Aunque el disco “quede bien”." },
  { n: 4, t: "La defensa puede tippear el pull si cae en brick.", v: false, r: "7.7", e: "No pueden tocarlo antes." },
  { n: 4, t: "Tras brick, con pivote y marca legal se puede contar.", v: true, r: "9.3", e: "El disco queda en juego." },
  { n: 4, t: "Tras brick hay 30 segundos sin conteo obligatorio.", v: false, r: "9.3", e: "Se aplica el conteo normal cuando corresponde." },
  { n: 4, t: "Falta y travel juntos no se resuelven solo por quién gritó primero.", v: true, r: "15 / 17 / 18", e: "Importa el tipo de infracción y la posesión." },
  { n: 4, t: "Siempre prevalece la primera palabra cantada.", v: false, r: "15", e: "No es un criterio único del reglamento." },
  { n: 4, t: "Pick demorado más de ~2 s es tarde.", v: true, r: "18.3.1.1", e: "Hay una ventana corta." },
  { n: 4, t: "Pick se puede guardar para el final de la jugada larga.", v: false, r: "18.3.1.1", e: "La demora máxima es breve." },
  { n: 4, t: "Handover ilegal en todo el campo.", v: true, r: "13.2.3", e: "También en endzone." },
  { n: 4, t: "En la zona de gol el handover es legal.", v: false, r: "13.2.3", e: "No lo es." },
  { n: 4, t: "Autopase ilegal aunque toque el piso primero (es turnover igual).", v: true, r: "13", e: "Piso = turnover; atraparlo vos no lo salva como autopase legal." },
  { n: 4, t: "Si el autopase pica primero, se vuelve legal.", v: false, r: "13.2.5", e: "El piso ya mató la posesión del ataque." },
  { n: 4, t: "Ratio mixta no se cambia libremente a mitad del punto.", v: true, r: "5.4", e: "Se define para el punto." },
  { n: 4, t: "En mixta podés meter 7 del mismo género si querés.", v: false, r: "5.4", e: "La proporción está regulada." },
  { n: 4, t: "Strip es distinto de tip.", v: true, r: "17.3 / 12", e: "Strip = soltar disco ya atrapado." },
  { n: 4, t: "Todo contacto con el disco del receptor es strip.", v: false, r: "17.3", e: "Tiene que haber habido posesión previa." },
  { n: 4, t: "Receptor a horcajadas sobre la línea de gol: no es gol.", v: true, r: "14.1 / 2.4", e: "Todos los apoyos deben estar en la zona de gol." },
  { n: 4, t: "Un pie en zona de gol alcanza para el gol.", v: false, r: "14.1", e: "Todos los apoyos en contacto con el suelo deben estar en la zona de gol." },
  { n: 4, t: "Conteo audible obligatorio.", v: true, r: "9.1", e: "El lanzador tiene que poder oírlo." },
  { n: 4, t: "Conteo susurrado es válido si hay costumbre.", v: false, r: "9.1", e: "Debe ser audible." },
  { n: 4, t: "Atacante fuera que toca el disco: disco out.", v: true, r: "11.7", e: "Aunque después caiga adentro." },
  { n: 4, t: "Atacante fuera puede tippear el disco hacia adentro legalmente.", v: false, r: "11.4 / 11.7", e: "Su contacto desde fuera saca el disco." },
  { n: 4, t: "Spirit timeout no es un timeout libre de cualquiera a mitad del punto.", v: true, r: "1 / Apéndice", e: "Tiene procedimientos específicos." },
  { n: 4, t: "Cualquiera pide spirit timeout cuando quiere como un timeout normal.", v: false, r: "Apéndice", e: "No funciona así." },
  { n: 4, t: "Travel aceptado corrige pivote; no premia reinicio a 1 automático.", v: true, r: "18.2.5 / 9.5", e: "El juego continúa." },
  { n: 4, t: "Todo travel aceptado pone el conteo en 1.", v: false, r: "9.5", e: "No es el efecto automático del travel." },
  { n: 4, t: "Gol lo define el receptor en la zona de gol, no el pivote del lanzador.", v: true, r: "14.1", e: "El lanzador puede estar en central." },
  { n: 4, t: "Para anotar el lanzador también debe estar en la zona de gol.", v: false, r: "14.1", e: "Solo importa la recepción en la zona." },
  { n: 4, t: "Blocking ilegal: moverse solo para tapar el camino del rival.", v: true, r: "12.7 / 17", e: "Sin jugar el disco." },
  { n: 4, t: "Cortar el camino del rival siempre es legal si no lo tocás.", v: false, r: "12.7", e: "Obstruir el movimiento puede ser falta." },
  { n: 5, t: "Si después de un stall-out contestado el juego se reanuda y vuelve a haber stall-out, el conteo otra vez arranca en 8.", v: true, r: "9.5.3", e: "Cada stall-out contestado se retoma con “Contando ocho”." },
  { n: 5, t: "Un jugador puede pedir una “continuation” después de una llamada si cree que la infracción no afectó la jugada.", v: false, r: "15 / 16", e: "No existe un pedido general de “continuation” por cualquier jugador; hay reglas específicas de juego limpio y resolución." },
  { n: 5, t: "Si hay falta compensatoria (ambos equipos tienen faltas aceptadas en la misma jugada), el conteo se reinicia en 1.", v: false, r: "17.9.1 / 9.5", e: "El disco vuelve al último lanzador no disputado; el reinicio del conteo sigue las reglas generales de reanudación." },
  { n: 5, t: "Un defensor fuera del campo puede tocar el disco en el aire si después cae dentro del campo.", v: true, r: "11.2 / 11.5", e: "Los defensores se consideran siempre dentro de los límites; pueden jugar el disco desde fuera." },
  { n: 5, t: "Después de un pull out-of-bounds, el ataque tiene 20 segundos para poner el disco en juego desde que lo recoge.", v: false, r: "8.5 / 7", e: "El plazo habitual para establecer el pivote tras un turnover/situación en zona central es de 10 segundos (20 si es en zona de gol)." },
  { n: 5, t: "Si se acepta un “pick” y el disco estaba en el aire, el receptor previsto se queda con el disco donde estaba al momento de la llamada.", v: false, r: "18.3 / 15.7", e: "Tras un pick, el juego se detiene y se reubican; no se “regala” automáticamente la recepción." },
  { n: 5, t: "Una falta de “blocking” ocurre cuando un jugador se mueve a la trayectoria de un rival exclusivamente para impedirle el paso, sin intentar jugar el disco.", v: true, r: "12.7 / 17", e: "No se puede obstruir el movimiento de un oponente de esa forma." },
  { n: 5, t: "Si el marcador dice “diez” exactamente cuando el disco sale de la mano del lanzador, no es stall-out.", v: true, r: "13.2.2 / 9.1", e: "Tiene que soltar el disco antes de que la marca empiece a decir “diez”; si ya lo soltó, el pase vale." },
  { n: 5, t: "En un partido a 15, si el marcador va 14-14, el siguiente gol gana sin necesidad de diferencia de 2.", v: true, r: "4.2", e: "Gana el primero que llega a 15; no hay obligación de ganar por 2 en el reglamento básico WFDF." },
  { n: 5, t: "Si un atacante atrapa el pull con un pie en la zona de gol que defiende, puede pedir brick igual.", v: false, r: "7.8 / 7.12", e: "Si un atacante toca el pull y no lo atrapa es pull caído; si lo atrapa, queda en posesión ahí (no es brick)." },
  { n: 5, t: "Un “spirit timeout” lo puede pedir cualquier jugador en cualquier momento del punto.", v: false, r: "1 / Apéndice", e: "Los procedimientos de espíritu tienen condiciones específicas; no es un timeout libre de cualquier jugador a mitad del punto." },
  { n: 5, t: "Si hay doble llamada (por ejemplo travel y falta) sobre la misma acción, se resuelve primero la que se cantó primero.", v: false, r: "15 / 17", e: "Se resuelven según el tipo de infracción y cómo afectan la posesión, no solo por quién gritó primero." },
  { n: 5, t: "Después de una infracción de “disco space” aceptada, el conteo se retoma como máximo en 6.", v: true, r: "9.5.4 / 9.5.5", e: "Como en la mayoría de las llamadas, el conteo vuelve como máximo a seis." },
  { n: 5, t: "Si el receptor establece posesión a horcajadas sobre la línea de gol (un pie en zona central y otro en zona de gol), es gol.", v: false, r: "14.1 / 2.4", e: "Para el gol, todos los puntos de apoyo en contacto con el suelo tienen que estar en la zona de gol." },
  { n: 5, t: "Si tras un stall-out contestado el conteo llega otra vez a stall-out y se vuelve a contestar, el conteo sigue retomándose en 8.", v: true, r: "9.5.3", e: "La regla del stall-out contestado se aplica cada vez." },
  { n: 5, t: "Un jugador en el aire que salió de dentro y todavía no tocó el suelo fuera sigue “adentro” hasta el aterrizaje.", v: true, r: "11.3.1", e: "El estado dentro/fuera se define al contactar el suelo (o fuera)." },
  { n: 5, t: "Si ambos equipos aceptan faltas en la misma jugada, se juega desde donde quedó el disco en el aire.", v: false, r: "17.9.1", e: "En faltas compensatorias el disco vuelve al último lanzador no disputado." },
  { n: 5, t: "El offside se cobra solo si el equipo rival lo canta; si nadie dice nada, el punto sigue.", v: true, r: "7.5 / 15", e: "Como casi todo en Ultimate, hay que cantarlo para que se aplique." },
  { n: 5, t: "Después de una infracción de marcaje aceptada, el conteo siempre vuelve a 1.", v: false, r: "9.5", e: "Según el caso vuelve a 1 o como máximo a 6; no siempre a 1." },
  { n: 5, t: "Un layout que llega al disco pero barre las piernas del rival es juego limpio si tocaste el disco primero.", v: false, r: "17.1 / 12.6", e: "Contacto ilegal o peligroso es falta aunque hayas tocado el disco." },
  { n: 5, t: "Si el lanzador pide tiempo muerto con el disco muerto (no en juego), no aplica la regla del +2 al conteo igual que en el punto.", v: true, r: "20.2 / 20.4", e: "La penalización de +2 es para el tiempo muerto indebido durante el punto / con conteo activo." },
  { n: 5, t: "Un receptor puede “bobblear” el disco (tocarlo varias veces) y aún así completar la captura si termina controlándolo.", v: true, r: "12.1", e: "La captura se establece cuando dejás de tener un disco girando y lo controlás, aunque antes haya rebotado en vos." },
  { n: 5, t: "Si pedís brick tarde, ya con el disco en la mano, el brick igual vale.", v: false, r: "7.12", e: "Hay que señalizarlo a tiempo, antes de levantar el disco." },
  { n: 5, t: "La marca puede contar con la mano señalando al mismo tiempo, pero no es obligatorio.", v: true, r: "9.1", e: "Lo obligatorio es el conteo audible con el ritmo correcto." },
  { n: 5, t: "Si un atacante está fuera y toca el disco, el disco queda fuera aunque después caiga adentro.", v: true, r: "11.7 / 11.4", e: "Contacto de un atacante fuera pone el disco fuera." },
  { n: 5, t: "Un spirit captain puede anular una falta cantada por su propio compañero.", v: false, r: "15.4 / 1", e: "Quien canta o retira su llamada es el jugador involucrado; el spirit captain no “pisa” faltas ajenas así." },
  { n: 5, t: "Después de un pick, el conteo se retoma como máximo en 6.", v: true, r: "9.5.5", e: "Como en la mayoría de las llamadas." },
  { n: 5, t: "Si el pull es tocado por la defensa antes de que lo toque el ataque o el suelo, es infracción aunque el disco caiga “bien”.", v: true, r: "7.7", e: "La defensa no puede tocar el pull antes." },
  { n: 5, t: "En caso de empate 14-14 en un partido a 15, se juega “universo” a diferencia de 2.", v: false, r: "4.2", e: "En el reglamento WFDF básico gana quien llega a 15; el win-by-2 es de formatos de torneo, no la regla general." },
  { n: 5, t: "Un “handover” (entregar el disco en la mano) es legal si ambos están quietos.", v: false, r: "13.2.3", e: "La entrega sin que el disco vuele es turnover." },
  { n: 5, t: "Si hay una parada técnica por lesión, el jugador lesionado puede quedarse en el campo sí o sí.", v: false, r: "19", e: "Según el caso puede tener que ser sustituido si no puede continuar." },
  { n: 5, t: "El wrapping causado únicamente porque el lanzador se metió debajo del brazo del defensor no es infracción del defensor.", v: true, r: "18.1.1.4", e: "Si la situación la causa solo el movimiento del lanzador, no se cobra wrapping." },
  { n: 5, t: "Si se acepta un travel, el pivote se corrige y el conteo no se reinicia automáticamente a 1.", v: true, r: "18.2.5 / 9.5", e: "El juego sigue; el conteo no “premia” un reinicio completo solo por travel." },
  { n: 5, t: "Un gol se puede anotar con el pivote todavía en la zona central si el receptor está en la zona de gol.", v: true, r: "14.1", e: "Quien tiene que estar en la zona de gol es el receptor que establece posesión, no el lanzador." },
  { n: 5, t: "Stall-out contestado reiterado sigue retomando en 8.", v: true, r: "9.5.3", e: "Cada vez." },
  { n: 5, t: "El segundo stall-out contestado se retoma en 5.", v: false, r: "9.5.3", e: "Sigue siendo 8." },
  { n: 5, t: "Estado en el aire se define al aterrizar.", v: true, r: "11.3.1", e: "Hasta entonces conservás el estado previo." },
  { n: 5, t: "Cruzar la línea en el aire ya te hace out.", v: false, r: "11.3.1", e: "Importa el primer contacto con el suelo/fuera." },
  { n: 5, t: "Faltas compensatorias no dejan el disco “donde estaba en el aire”.", v: true, r: "17.9.1", e: "Vuelven al último lanzador no disputado." },
  { n: 5, t: "Faltas compensatorias: posesión donde iba a caer el disco.", v: false, r: "17.9.1", e: "Se vuelve al lanzador previo claro." },
  { n: 5, t: "Infracción de marcaje aceptada no siempre reinicia en 1.", v: true, r: "9.5", e: "A veces máx. en 6." },
  { n: 5, t: "Toda infracción de marcaje pone el conteo en 1.", v: false, r: "9.5", e: "Depende del tipo." },
  { n: 5, t: "Tocar el disco primero no limpia un layout ilegal.", v: true, r: "17.1 / 12.6", e: "El contacto ilegal sigue siendo falta." },
  { n: 5, t: "Si tocás el disco antes que al rival, el contacto posterior es legal.", v: false, r: "12.6", e: "No justifica iniciar contacto." },
  { n: 5, t: "Bobble + control final puede ser captura.", v: true, r: "12.1", e: "La posesión se establece al controlar." },
  { n: 5, t: "Un bobble anula siempre la jugada.", v: false, r: "12.1", e: "Podés terminar de atrapar." },
  { n: 5, t: "Brick tarde (disco ya en mano) no vale.", v: true, r: "7.12", e: "Señal antes de levantarlo." },
  { n: 5, t: "Brick se puede pedir en cualquier momento del punto.", v: false, r: "7.12", e: "Es una opción tras ciertos pulls, a tiempo." },
  { n: 5, t: "Señalizar el conteo con la mano es opcional.", v: true, r: "9.1", e: "Lo obligatorio es el conteo audible." },
  { n: 5, t: "Sin gestos con la mano el conteo es inválido.", v: false, r: "9.1", e: "No es un requisito." },
  { n: 5, t: "Spirit captain no anula faltas de sus compañeros.", v: true, r: "15.4 / 1", e: "La llamada es del jugador involucrado." },
  { n: 5, t: "El spirit captain puede borrar cualquier falta del equipo.", v: false, r: "1", e: "No tiene ese poder." },
  { n: 5, t: "Win-by-2 no es la regla general WFDF a 15.", v: true, r: "4.2", e: "Gana quien llega a 15; formatos de torneo pueden agregar universo." },
  { n: 5, t: "14-14 siempre exige ganar por 2 en el reglamento básico.", v: false, r: "4.2", e: "Eso es regla de formato, no la general." },
  { n: 5, t: "Handover ilegal aunque estén quietos.", v: true, r: "13.2.3", e: "Debe volar el disco." },
  { n: 5, t: "Handover quieto es legal en stall 9.", v: false, r: "13.2.3", e: "Nunca es legal." },
  { n: 5, t: "Wrapping causado solo por el lanzador no se cobra al defensor.", v: true, r: "18.1.1.4", e: "Misma lógica que disco space." },
  { n: 5, t: "Si hay brazo sobre pivote siempre es wrapping del defensor.", v: false, r: "18.1.1.4", e: "Hay excepción si lo causa el lanzador." },
  { n: 5, t: "Pick aceptado no “regala” la recepción automáticamente.", v: true, r: "18.3 / 15.7", e: "Se reubican / se resuelve según la regla." },
  { n: 5, t: "Pick con disco en el aire = receptor se queda con el disco siempre.", v: false, r: "18.3", e: "No es automático." },
  { n: 5, t: "Decir “diez” cuando el disco ya salió: no es stall-out.", v: true, r: "13.2.2", e: "Tiene que empezar “diez” antes del release." },
  { n: 5, t: "Si “diez” y el release son al mismo tiempo, siempre es stall.", v: false, r: "13.2.2", e: "Debe soltar antes de que empiece a decirse “diez”." },
  { n: 5, t: "Atrapar el pull en tu endzone no te da brick.", v: true, r: "7.8 / 7.12", e: "Si lo atrapás, poseés ahí." },
  { n: 5, t: "Atrapar el pull en tu endzone permite brick igual.", v: false, r: "7.12", e: "Brick es para ciertos pulls no atrapados/out." },
  { n: 5, t: "Doble llamada no se ordena solo por quién gritó primero.", v: true, r: "15 / 17", e: "Se mira el efecto sobre la posesión." },
  { n: 5, t: "La primera llamada siempre cancela a la segunda.", v: false, r: "15", e: "No es la regla." },
  { n: 5, t: "Disco space aceptado: conteo máx. en 6.", v: true, r: "9.5.4 / 9.5.5", e: "Como la mayoría." },
  { n: 5, t: "Disco space aceptado: conteo en 1 siempre.", v: false, r: "9.5", e: "Máximo en 6." },
  { n: 5, t: "Defensor out puede tocar el disco.", v: true, r: "11.2", e: "Se lo considera in-bounds." },
  { n: 5, t: "Defensor con pie sobre la línea lateral no puede tippear.", v: false, r: "11.2", e: "Puede jugar el disco." },
  { n: 5, t: "Continuation genérica pedida por cualquiera no existe.", v: true, r: "15 / 16", e: "Hay reglas específicas, no un comodín." },
  { n: 5, t: "Cualquiera canta “continuation” y se ignora la falta.", v: false, r: "15", e: "No funciona así." },
  { n: 5, t: "Lesión: el jugador puede tener que salir si no continúa.", v: true, r: "19", e: "No se queda “sí o sí”." },
  { n: 5, t: "Toda parada técnica por lesión obliga a dejar al jugador dentro.", v: false, r: "19", e: "Puede requerir sustitución." },
  { n: 5, t: "Pull out: pivote con plazos de 10 s en central.", v: true, r: "8.5 / 7", e: "No 20 s salvo zona de gol." },
  { n: 5, t: "Pull out: siempre 20 s para poner el disco.", v: false, r: "8.5", e: "20 s es para zona de gol." },
  { n: 5, t: "Falta compensatoria no fuerza conteo en 1 por sí sola.", v: true, r: "17.9.1 / 9.5", e: "Vuelve el disco al lanzador; el conteo sigue reglas de reanudación." },
  { n: 5, t: "Falta compensatoria = stall count 1 automático.", v: false, r: "9.5", e: "No es esa la regla automática." },
  { n: 5, t: "Travel no se “activa” solo: alguien debe cantarlo para cobrarse.", v: true, r: "15 / 18.2", e: "Como el resto de infracciones autoarbitradas." },
  { n: 5, t: "Un travel existe aunque nadie lo diga y anula el pase solo.", v: false, r: "15", e: "Sin llamada, el juego sigue." },
  { n: 5, t: "Universo/win-by-2 es típico de formatos, no del 4.2 puro.", v: true, r: "4.2", e: "El reglamento base es a 15." },
  { n: 5, t: "El reglamento WFDF obliga universo en todo partido a 15.", v: false, r: "4.2", e: "No lo obliga como regla general." },
  { n: 5, t: "Strip ≠ tip en el intento de recepción.", v: true, r: "17.3", e: "Strip es después de la captura." },
  { n: 5, t: "Tip del defensor en la recepción es strip.", v: false, r: "17.3", e: "Si no había posesión, no es strip." },
  { n: 5, t: "Offside de ataque y de defensa tienen procedimientos distintos.", v: true, r: "7.5", e: "No se resuelven igual." },
  { n: 5, t: "Todo offside se resuelve igual sin importar quién se adelantó.", v: false, r: "7.5", e: "Ataque y defensa tienen tratamientos distintos." },
  { n: 5, t: "Reanudar tras pick implica reubicación.", v: true, r: "18.3", e: "Se restaura el estado previo a la obstrucción." },
  { n: 5, t: "Tras pick el juego sigue sin reubicar a nadie.", v: false, r: "18.3", e: "La idea del pick es reestablecer posiciones." },
  { n: 5, t: "Conteo tras la mayoría de llamadas: máx. 6.", v: true, r: "9.5.5", e: "Con excepciones (p. ej. stall contestado en 8, ciertas en 1 o 9)." },
  { n: 5, t: "Tras cualquier llamada el conteo vuelve siempre a 1.", v: false, r: "9.5", e: "Hay varios reinicios posibles." },
  { n: 5, t: "Pivote en endzone propia tras turnover: 20 s.", v: true, r: "8.5.1.2", e: "Zona de gol." },
  { n: 5, t: "Pivote en endzone propia tras turnover: 10 s.", v: false, r: "8.5.1.2", e: "En zona de gol son 20." },
  { n: 5, t: "Un pase puede ser tippeado por varios y seguir vivo.", v: true, r: "12 / 13", e: "Hasta que alguien posea o toque el piso/out." },
  { n: 5, t: "El segundo tip automático es turnover.", v: false, r: "12", e: "No hay esa regla." },
  { n: 5, t: "Marcador que pierde distancia reinicia, no “pausá y seguí”.", v: true, r: "9.3.2", e: "Debe volver a empezar el conteo." },
  { n: 5, t: "Marcador que se aleja puede volver y seguir en el mismo número.", v: false, r: "9.3.2", e: "Reinicia." },
  { n: 5, t: "El lanzador del tiempo muerto indebido sufre +2 al stall.", v: true, r: "20.4", e: "Puede stall-out." },
  { n: 5, t: "Tiempo muerto indebido solo advierte verbalmente.", v: false, r: "20.4", e: "Hay penalización de conteo." },
  { n: 5, t: "Receptor con posesión en endzone: gol, aunque el defensor diga “no fue control”.", v: true, r: "14.1 / 12", e: "Si hubo captura real, es gol; se puede discutir el control." },
  { n: 5, t: "El defensor puede anular un gol solo gritándolo más fuerte.", v: false, r: "1 / 14", e: "Se discute con criterios de posesión, no por volumen." },
];
